<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by LaravelMigration.spBundle
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateHobbyUserTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('hobby_user', function (Blueprint $table) {            
            $table->increments('id');
            $table->integer('user_id')->unsigned()->nullable();            
            $table->integer('hobby_id')->unsigned()->nullable();            

            $table->index(['user_id', 'hobby_id'], 'user_id');
            $table->index('hobby_id', 'hobby_id');

            $table->foreign('hobby_id', 'hobby_user_ibfk_2')->references('id')->on('hobbies')->onDelete('RESTRICT
')->onUpdate('CASCADE');
            $table->foreign('user_id', 'hobby_user_ibfk_1')->references('id')->on('users')->onDelete('CASCADE
')->onUpdate('CASCADE');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('hobby_user');
    }
}
